### GET
GET http://localhost:8080/coffee/list

### GET
GET http://localhost:8080/coffee/reload

### GET
GET http://localhost:8080/coffee/get/latte

### GET
GET http://localhost:8080/coffee/delete/latte

### Coffee Post
POST http://localhost:8080/coffee/update
Content-Type: application/json

{
    "id": 2,
    "name": "latte",
    "price": 1000
}

### POST
POST http://localhost:8080/order/ HTTP/1.1
content-type: application/json

{
    "customer": "latte",
    "items": ["1","2"]
}

### Coffee Post 测试 validate(表单模式)
POST http://localhost:8080/coffee/save?name=latte&price=1000
Content-Type: application/x-www-form-urlencoded
### v2 捕获异常，返回结果
POST http://localhost:8080/coffee/savev2?name=latte
Content-Type: application/x-www-form-urlencoded
